// Generated by CoffeeScript 1.3.3
(function() {
  var Exemplar, NULL_TYPE_NAME, isArray,
    __hasProp = {}.hasOwnProperty,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  NULL_TYPE_NAME = 'null';

  isArray = Array.isArray || function(obj) {
    return (obj != null ? obj.toString() : void 0) === '[object Array]';
  };

  module.exports = Exemplar = (function() {

    function Exemplar(options) {
      options || (options = {});
      this.disallowExtraKeys = options.disallowExtraKeys || false;
      this.ignoredKeys = options.ignoredKeys || [];
      this.allowedTypeNamesByKey = {};
    }

    Exemplar.prototype.typeNameFor = function(val) {
      var child, childType, childTypes, _i, _len;
      if (!(val != null)) {
        return NULL_TYPE_NAME;
      } else if (isArray(val)) {
        childTypes = (function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = val.length; _i < _len; _i++) {
            child = val[_i];
            _results.push(this.typeNameFor(child));
          }
          return _results;
        }).call(this);
        if (childTypes.length === 0) {
          return '[*]';
        } else {
          for (_i = 0, _len = childTypes.length; _i < _len; _i++) {
            childType = childTypes[_i];
            if (childType !== childTypes[0]) {
              return '[*]';
            }
          }
          return '[' + childTypes[0] + ']';
        }
      } else {
        return typeof val;
      }
    };

    Exemplar.prototype.addExample = function(ex) {
      var allowedTypeNames, key, typeName, val, _base, _ref, _results;
      for (key in ex) {
        if (!__hasProp.call(ex, key)) continue;
        val = ex[key];
        if (__indexOf.call(this.ignoredKeys, key) < 0) {
          typeName = this.typeNameFor(val);
          allowedTypeNames = ((_base = this.allowedTypeNamesByKey)[key] || (_base[key] = []));
          if (__indexOf.call(allowedTypeNames, typeName) < 0) {
            allowedTypeNames.push(typeName);
          }
        }
      }
      _ref = this.allowedTypeNamesByKey;
      _results = [];
      for (key in _ref) {
        allowedTypeNames = _ref[key];
        if (!(ex[key] != null)) {
          if (__indexOf.call(allowedTypeNames, NULL_TYPE_NAME) < 0) {
            _results.push(allowedTypeNames.push(NULL_TYPE_NAME));
          } else {
            _results.push(void 0);
          }
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Exemplar.prototype.check = function(o) {
      var allowedTypeNames, key, typeName, val;
      if (typeof o !== 'object') {
        return false;
      }
      for (key in o) {
        if (!__hasProp.call(o, key)) continue;
        val = o[key];
        if (__indexOf.call(this.ignoredKeys, key) < 0) {
          typeName = this.typeNameFor(val);
          allowedTypeNames = this.allowedTypeNamesByKey[key];
          if (allowedTypeNames != null) {
            if (__indexOf.call(allowedTypeNames, typeName) < 0) {
              return false;
            }
          } else {
            if (this.disallowExtraKeys) {
              return false;
            }
          }
        }
      }
      return true;
    };

    Exemplar.prototype.inspect = function() {
      return "[Exemplar: " + this.allowedTypeNamesByKey + "]";
    };

    return Exemplar;

  })();

}).call(this);
